version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - ENV_WITH_SECRETS
    working_dir: /app
    ports:
      - "3000:3000"
    image: biblioteca-app
    env_file:
      - .env
      
secrets:
  ENV_WITH_SECRETS:
    file: .env