name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - run: npm ci

  docker-build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: ibisg/biblioteca:latest
          secrets: |
            "ENV_WITH_SECRETS=${{ secrets.ENV_WITH_SECRETS_DEV }}"