name: Docker
env:
  ENV_FILE: ${{ contains(github.ref_name, '-dev') && secrets.ENV_WITH_SECRETS_DEV || secrets.ENV_WITH_SECRETS }}
on:
  push:
    tags:
      - v*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ibisg/biblioteca:${{github.ref_name}}
          secrets: |
            "ENV_WITH_SECRETS=${{ env.ENV_FILE }}"
